import React from 'react';
import Icon from 'react-native-vector-icons/Ionicons';
import { ColorValue } from 'react-native';

interface AppIconProps {
  name: string;
  size?: number;
  color?: string | ColorValue;
  style?: any;
}

const ICON_MAP: Record<string, string> = {
  home: 'home',
  homeOutline: 'home-outline',
  chatbubble: 'chatbubble',
  chatbubbleOutline: 'chatbubble-outline',
  medical: 'medkit',
  medicalOutline: 'medkit-outline',
  heart: 'heart',
  heartOutline: 'heart-outline',
  nutrition: 'restaurant',
  nutritionOutline: 'restaurant-outline',
  fitness: 'barbell',
  fitnessOutline: 'barbell-outline',
  pill: 'medkit-sharp',
  reminder: 'notifications',
  reminderOutline: 'notifications-outline',
  search: 'search',
  searchOutline: 'search-outline',
  download: 'download',
  downloadOutline: 'cloud-download-outline',
  settings: 'settings',
  settingsOutline: 'settings-outline',
  menu: 'menu',
  close: 'close',
  arrowForward: 'arrow-forward',
  arrowBack: 'arrow-back',
  send: 'send',
  mic: 'mic',
  micOutline: 'mic-outline',
  attach: 'attach',
  copy: 'copy-outline',
  volumeHigh: 'volume-high',
  volumeHighOutline: 'volume-high-outline',
  moon: 'moon',
  moonOutline: 'moon-outline',
  sunny: 'sunny',
  sunnyOutline: 'sunny-outline',
  person: 'person',
  personOutline: 'person-outline',
  people: 'people',
  peopleOutline: 'people-outline',
  hospital: 'business',
  hospitalOutline: 'business-outline',
  leaf: 'leaf',
  leafOutline: 'leaf-outline',
  information: 'information-circle',
  informationOutline: 'information-circle-outline',
  brain: 'hardware-chip',
  brainOutline: 'hardware-chip-outline',
  checkmark: 'checkmark',
  checkmarkCircle: 'checkmark-circle',
  warning: 'warning',
  warningOutline: 'warning-outline',
  error: 'close-circle',
  errorOutline: 'close-circle-outline',
  star: 'star',
  starOutline: 'star-outline',
  filter: 'filter',
  eye: 'eye',
  eyeOutline: 'eye-outline',
  lockClosed: 'lock-closed',
  lockClosedOutline: 'lock-closed-outline',
  mail: 'mail',
  mailOutline: 'mail-outline',
  logoGoogle: 'logo-google',
  logoApple: 'logo-apple',
  signOut: 'log-out-outline',
  chevronDown: 'chevron-down',
  chevronForward: 'chevron-forward',
  refresh: 'refresh',
  trash: 'trash',
  document: 'document-text',
  image: 'image',
  globe: 'globe-outline',
  sparkle: 'sparkles',
  sparkleOutline: 'sparkles-outline',
  list: 'list',
  grid: 'grid',
  bolt: 'bolt',
  pulse: 'pulse',
  body: 'body',
  stethoscope: 'stethoscope',

  'bookmark-outline': 'bookmark-outline',
  archive: 'archive',
  calendar: 'calendar-outline',
  briefcase: 'briefcase-outline',
  'shield-checkmark': 'shield-checkmark',
  'notifications-outline': 'notifications-outline',

  // Navigation & UI
  'arrow-back': 'arrow-back',
  'arrow-forward': 'arrow-forward',
  'chevron-right': 'chevron-forward',
  'chevron-left': 'chevron-back',
  'chevron-down': 'chevron-down',
  'chevron-up': 'chevron-up',
  'expand-more': 'chevron-down',
  'expand-less': 'chevron-up',
  add: 'add',
  'add-circle': 'add-circle',
  'add-comment': 'chatbubble-outline',
  check: 'checkmark',
  'check-circle': 'checkmark-circle',
  delete: 'trash',
  'delete-outline': 'trash-outline',
  edit: 'pencil',
  'open-in-new': 'open-outline',
  'more-vert': 'ellipsis-vertical',
  'more-horiz': 'ellipsis-horizontal',

  // Health & Medical
  alarm: 'alarm',
  'alarm-off': 'alarm-outline',
  'monitor-heart': 'pulse',
  thermostat: 'thermometer',
  straighten: 'resize-outline',
  'fitness-center': 'barbell',
  'add-task': 'add-circle',
  biomarker: 'flask',
  science: 'flask',
  'local-pharmacy': 'medkit',
  'medication-liquid': 'flask',

  // Emergency
  emergency: 'alert-circle',
  'local-police': 'shield',
  'person-add': 'person-add',
  ban: 'ban',
  block: 'ban',
  skull: 'skull',
  dangerous: 'skull',

  // Maps & Location
  map: 'map',
  directions: 'navigate',
  'location-off': 'location-outline',
  location: 'location',
  'my-location': 'locate',

  // Communication
  phone: 'call',
  'chat-bubble': 'chatbubble',
  'chat-bubble-outline': 'chatbubble-outline',
  translate: 'language',

  // Actions
  savings: 'cash-outline',
  'search-off': 'search-outline',
  'person-outline': 'person-outline',
  dashboard: 'grid',
  groups: 'people',
  info: 'information-circle',
  'bolt-icon': 'flash',
  whatshot: 'flame',
  flame: 'flame',
  bug: 'bug',
  'pest-control': 'bug',
  'airline-seat-flat': 'bed',
  bed: 'bed',

  // Agent icons
  'medical-services': 'medical',
  'medical-services-outline': 'medical-outline',
  'local-hospital': 'medkit',
  'local-hospital-outline': 'medkit-outline',
  'child-care': 'child',
  'child-care-outline': 'child-outline',
  healing: 'pulse',
  'healing-outline': 'pulse-outline',
  favorite: 'heart',
  'favorite-outline': 'heart-outline',
  face: 'happy',
  'face-outline': 'happy-outline',
  psychology: 'brain',
  'psychology-outline': 'brain-outline',
  air: 'water-outline',
  'air-outline': 'water-outline',
  'water-drop': 'water',
  'water-drop-outline': 'water-outline',
  biotech: 'flask',
  'biotech-outline': 'flask-outline',
  coronavirus: 'bug',
  'coronavirus-outline': 'bug-outline',
  'pregnant-woman': 'woman',
  'pregnant-woman-outline': 'woman-outline',
  'accessibility-new': 'accessibility',
  'accessibility-new-outline': 'accessibility-outline',
  visibility: 'eye',
  'visibility-outline': 'eye-outline',
  hearing: 'hearing',
  'hearing-outline': 'hearing-outline',
  'self-improvement': 'self-improvement',
  'self-improvement-outline': 'self-improvement-outline',
  masks: 'medical',
  'masks-outline': 'medical-outline',
  wc: 'male-female',
  'wc-outline': 'male-female-outline',
  bloodtype: 'water',
  'bloodtype-outline': 'water-outline',
  accessibility: 'accessibility',
  'accessibility-outline': 'accessibility-outline',
  grass: 'leaf',
  'grass-outline': 'leaf-outline',
  crib: 'bed',
  'crib-outline': 'bed-outline',
  elderly: 'accessibility',
  'elderly-outline': 'accessibility-outline',
  'set-meal': 'restaurant',
  'set-meal-outline': 'restaurant-outline',
  medication: 'medkit',
  'medication-outline': 'medkit-outline',
};

export function getIconName(key: string): string {
  return ICON_MAP[key] || key;
}

export function AppIcon({ name, size = 22, color, style }: AppIconProps) {
  const iconName = ICON_MAP[name] || name;
  return <Icon name={iconName} size={size} color={color as string} style={style} />;
}